-- Ficha tecnica del cliente: datos personales e historia clinica.
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS document_id text,
  ADD COLUMN IF NOT EXISTS blood_type text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS health_insurance text,
  ADD COLUMN IF NOT EXISTS landline text,
  ADD COLUMN IF NOT EXISTS companion_name text,
  ADD COLUMN IF NOT EXISTS companion_relationship text,
  ADD COLUMN IF NOT EXISTS family_history text,
  ADD COLUMN IF NOT EXISTS allergies text,
  ADD COLUMN IF NOT EXISTS diseases text,
  ADD COLUMN IF NOT EXISTS cancer text,
  ADD COLUMN IF NOT EXISTS antidepressants text,
  ADD COLUMN IF NOT EXISTS arrhythmia text,
  ADD COLUMN IF NOT EXISTS pacemaker text,
  ADD COLUMN IF NOT EXISTS fatty_liver text,
  ADD COLUMN IF NOT EXISTS surgeries text,
  ADD COLUMN IF NOT EXISTS hernias text,
  ADD COLUMN IF NOT EXISTS stomach_mesh text,
  ADD COLUMN IF NOT EXISTS implants text,
  ADD COLUMN IF NOT EXISTS last_period date,
  ADD COLUMN IF NOT EXISTS alcohol text,
  ADD COLUMN IF NOT EXISTS smoking text,
  ADD COLUMN IF NOT EXISTS medications text,
  ADD COLUMN IF NOT EXISTS skin_biotype text,
  ADD COLUMN IF NOT EXISTS skin_phototype text;
